name: Sync ORCID publications

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1' # weekly
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run ORCID fetcher
        env:
          ORCID_CLIENT_ID: ${{ secrets.ORCID_CLIENT_ID }}
          ORCID_CLIENT_SECRET: ${{ secrets.ORCID_CLIENT_SECRET }}
        run: |
          python scripts/fetch_orcid.py

      - name: Commit generated publications
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _publications || true
          if ! git diff-index --quiet HEAD --; then
            git commit -m "update publications from ORCID"
            git push
          else
            echo "No changes"
          fi
